name: 'Secure Checkout'
description: 'Checkout with pre-cleanup for Docker permission issues and optional post-setup'

inputs:
  fetch-depth:
    description: 'Number of commits to fetch (0 = all history)'
    required: false
    default: '0'
  token:
    description: 'GitHub token for checkout'
    required: false
    default: ${{ github.token }}
  ref:
    description: 'Branch/ref to checkout'
    required: false
    default: ''
  lfs:
    description: 'Fetch LFS objects'
    required: false
    default: 'true'
  init-output-dirs:
    description: 'Initialize output directories after checkout'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    # Pre-checkout cleanup: Remove Docker-created directories that cause permission errors
    # This must run BEFORE checkout because checkout's clean:true can't delete root-owned files
    - name: Pre-checkout cleanup
      shell: bash
      run: |
        # Always attempt cleanup - rm -rf succeeds even if directories don't exist
        # This must run unconditionally to handle root-owned files from previous Docker runs
        docker run --rm -v "$(pwd):/workspace" busybox sh -c "rm -rf /workspace/outputs /workspace/evaluation_results" || true

    - name: Checkout code
      uses: actions/checkout@v6
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        clean: true
        token: ${{ inputs.token }}
        ref: ${{ inputs.ref }}
        lfs: ${{ inputs.lfs }}

    - name: Post-checkout setup
      if: inputs.init-output-dirs == 'true'
      shell: bash
      run: |
        # Initialize output directories to prevent root ownership issues
        if [ -f "./automation/setup/docker/init-output-dirs.sh" ]; then
          ./automation/setup/docker/init-output-dirs.sh
        fi
