name: Dependency Updates

on:
  schedule:
    # Run weekly on Monday at 3 AM UTC
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools safety

      - name: Update requirements
        run: |
          # Create requirements.in from current requirements
          cp requirements-cgt.txt requirements.in

          # Compile updated requirements
          pip-compile --upgrade --resolver=backtracking requirements.in -o requirements-cgt-new.txt

          # Check for changes
          if ! diff -q requirements-cgt.txt requirements-cgt-new.txt > /dev/null; then
            mv requirements-cgt-new.txt requirements-cgt.txt
            echo "DEPS_UPDATED=true" >> $GITHUB_ENV
          else
            echo "No dependency updates available"
            echo "DEPS_UPDATED=false" >> $GITHUB_ENV
          fi

      - name: Run safety check
        if: env.DEPS_UPDATED == 'true'
        run: |
          safety check -r requirements-cgt.txt --json > safety-report.json || true

          # Check if there are any vulnerabilities
          if grep -q '"vulnerabilities": \[\]' safety-report.json; then
            echo "No vulnerabilities found"
          else
            echo "⚠️ Security vulnerabilities found in dependencies"
            cat safety-report.json
          fi

      - name: Test with updated dependencies
        if: env.DEPS_UPDATED == 'true'
        run: |
          pip install -r requirements-cgt.txt
          pip install -e .

          # Run basic smoke tests
          export PYTHONPATH=${{ github.workspace }}/src:$PYTHONPATH
          python -c "from validators.oregon import OregonValidator; print('Import test passed')"
          cgt-validate --help

      - name: Create Pull Request
        if: env.DEPS_UPDATED == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies"
          title: "Automated Dependency Updates"
          body: |
            ## Automated Dependency Updates

            This PR contains automated dependency updates generated by pip-compile.

            ### Changes
            See the diff for detailed changes to requirements-cgt.txt

            ### Security Check
            Safety check has been run on the updated dependencies.

            ### Testing
            - ✅ Basic import tests passed
            - ✅ CLI smoke test passed

            Please review and run full test suite before merging.
          branch: automated-dependency-updates
          delete-branch: true
