# Secrets Configuration for Automatic Masking
# This configuration ensures secrets are never exposed in public GitHub comments
# Used by all AI agents and automation tools

version: "1.0.0"
description: "Central configuration for automatic secret masking in public outputs"

# Environment variables that contain secrets
# These will be masked if their values appear in any GitHub comment
environment_variables:
  # GitHub tokens and authentication
  - GITHUB_TOKEN
  - GH_TOKEN
  - AI_AGENT_TOKEN

  # API keys for various services
  - OPENROUTER_API_KEY
  - ANTHROPIC_API_KEY
  - OPENAI_API_KEY
  - GEMINI_API_KEY
  - CLAUDE_API_KEY

  # Database passwords
  - DB_PASSWORD
  - DATABASE_PASSWORD
  - POSTGRES_PASSWORD
  - MYSQL_PASSWORD
  - REDIS_PASSWORD

  # Application secrets
  - SECRET_KEY
  - JWT_SECRET
  - SESSION_SECRET
  - WEBHOOK_SECRET
  - WEBHOOK_URL

  # Cloud provider credentials
  - AWS_ACCESS_KEY_ID
  - AWS_SECRET_ACCESS_KEY
  - AWS_SESSION_TOKEN
  - GOOGLE_API_KEY
  - GOOGLE_CLIENT_SECRET
  - AZURE_CLIENT_SECRET

  # Container registry credentials
  - DOCKER_PASSWORD
  - DOCKER_HUB_PASSWORD

  # Package registry tokens
  - NPM_TOKEN
  - PYPI_TOKEN

  # Communication service tokens
  - SLACK_TOKEN
  - SLACK_WEBHOOK_URL
  - DISCORD_TOKEN
  - DISCORD_WEBHOOK_URL
  - TELEGRAM_BOT_TOKEN

  # Payment service keys
  - STRIPE_SECRET_KEY
  - STRIPE_WEBHOOK_SECRET
  - PAYPAL_CLIENT_SECRET

  # Email service keys
  - SENDGRID_API_KEY
  - MAILGUN_API_KEY
  - TWILIO_AUTH_TOKEN

  # Cryptographic keys
  - SSH_PRIVATE_KEY
  - GPG_PRIVATE_KEY
  - ENCRYPTION_KEY

  # Generic secrets
  - API_SECRET
  - CLIENT_SECRET
  - PRIVATE_KEY
  - ACCESS_TOKEN
  - REFRESH_TOKEN
  - BEARER_TOKEN
  - AUTH_TOKEN

  # Service URLs (may contain embedded credentials)
  - COMFYUI_SERVER_URL
  - AI_TOOLKIT_SERVER_URL
  - GAEA2_REMOTE_URL

# Patterns for detecting secrets by format
# These regex patterns identify common secret formats
patterns:
  - name: GITHUB_TOKEN
    pattern: "ghp_[A-Za-z0-9_]{36,}"
    description: "GitHub personal access token"

  - name: GITHUB_SECRET
    pattern: "ghs_[A-Za-z0-9_]{36,}"
    description: "GitHub secret"

  - name: GITHUB_PAT
    pattern: "github_pat_[A-Za-z0-9_]{22,}"
    description: "GitHub personal access token (new format)"

  - name: GITHUB_OAUTH
    pattern: "gho_[A-Za-z0-9_]{36,}"
    description: "GitHub OAuth token"

  - name: API_KEY
    pattern: "sk-[A-Za-z0-9\\-]{32,}"
    description: "Generic API key (OpenAI style)"

  - name: PRIVATE_KEY
    pattern: "pk-[A-Za-z0-9\\-]{32,}"
    description: "Generic private key"

  - name: BEARER_TOKEN
    pattern: "Bearer\\s+[A-Za-z0-9\\-_=]{20,}"
    description: "Bearer authentication token"

  - name: URL_WITH_AUTH
    pattern: "https?://[^:\\s]+:[^@\\s]+@[^\\s]+"
    description: "URL with embedded credentials"

  - name: AWS_ACCESS_KEY
    pattern: "AKIA[0-9A-Z]{16}"
    description: "AWS access key ID"

  - name: JWT_TOKEN
    pattern: "eyJ[A-Za-z0-9\\-_=]+\\.[A-Za-z0-9\\-_=]+\\.[A-Za-z0-9\\-_=]+"
    description: "JSON Web Token"

  - name: PRIVATE_KEY_BLOCK
    pattern: "-----BEGIN[A-Z\\s]+PRIVATE KEY-----[\\s\\S]+?-----END[A-Z\\s]+PRIVATE KEY-----"
    description: "Private key block (RSA, EC, etc.)"

  - name: SSH_KEY
    pattern: "ssh-rsa\\s+[A-Za-z0-9+/]{100,}"
    description: "SSH public key"

  - name: SLACK_TOKEN
    pattern: "xox[baprs]-[0-9]{10,}-[A-Za-z0-9]{24,}"
    description: "Slack token"

  - name: STRIPE_KEY
    pattern: "(sk|pk)_(test|live)_[A-Za-z0-9]{24,}"
    description: "Stripe API key"

  - name: NPM_TOKEN
    pattern: "npm_[A-Za-z0-9]{36}"
    description: "NPM access token"

# Auto-detection rules for environment variables
auto_detection:
  enabled: true

  # Patterns that indicate a variable contains secrets
  # Uses glob-style patterns (* = any characters)
  include_patterns:
    - "*_TOKEN"
    - "*_SECRET"
    - "*_KEY"
    - "*_PASSWORD"
    - "*_PASS"
    - "*_PWD"
    - "*_CREDENTIAL*"
    - "*_AUTH"
    - "TOKEN_*"
    - "SECRET_*"
    - "KEY_*"
    - "PASSWORD_*"
    - "API_*"
    - "PRIVATE_*"

  # Patterns to exclude from auto-detection
  # These are typically safe to expose
  exclude_patterns:
    - "PUBLIC_KEY"
    - "PUBLIC_*"
    - "*_PUBLIC"
    - "*_PUBLIC_*"
    - "ENABLE_*"
    - "*_ENABLED"
    - "*_DISABLED"

# Settings for the masking behavior
settings:
  # Minimum length for a value to be considered a secret
  minimum_secret_length: 4

  # Whether pattern matching is case-sensitive
  case_sensitive_patterns: false

  # Whether to mask partial matches
  mask_partial_matches: false

  # Whether to log when secrets are masked (to stderr)
  log_masked_secrets: true

  # Format for masked values
  # {name} will be replaced with the variable/pattern name
  mask_format: "[MASKED_{name}]"
