# Override file for running video editor without GPU
version: '3.8'

services:
  mcp-video-editor:
    environment:
      - ENABLE_GPU=false
      - WHISPER_DEVICE=cpu
      - DIART_DEVICE=cpu
    deploy:
      resources:
        limits:
          memory: 4G
    # Remove GPU requirements - override by setting to empty
    runtime: ""
