version: '3.8'

services:
  ai-agents:
    build:
      context: .
      dockerfile: docker/ai-agents.Dockerfile
    container_name: ai-agents
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    volumes:
      - ./:/workspace
      # Mount secrets from host directory (created by GitHub Actions)
      - type: bind
        source: ${SECRETS_DIR:-./.secrets}
        target: /run/secrets
        read_only: true
    environment:
      - PYTHONUNBUFFERED=1
      - GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
      - ENABLE_AUTO_FIX=${ENABLE_AUTO_FIX:-false}
      # Remove GITHUB_TOKEN from environment - use secrets instead
    working_dir: /workspace
    networks:
      - mcp-network
    command: ["/bin/bash"]
    tty: true
    stdin_open: true
    profiles:
      - agents

networks:
  mcp-network:
    driver: bridge
