//! Local storage of generated audio: writing files into the dated output
//! directory and cleaning up previously generated files.
//!
//! Only files this server created are ever deleted: names must start with a
//! known prefix (`speech_`, `sfx_`) and end in a known audio extension, and
//! only the output directory and its immediate `YYYY-MM-DD` subdirectories
//! are scanned (no recursion, symlinks are skipped).

use serde::Serialize;
use std::path::{Path, PathBuf};
use std::time::{Duration, SystemTime};

/// File name prefix for synthesized speech.
pub const SPEECH_PREFIX: &str = "speech_";
/// File name prefix for sound effects.
pub const SFX_PREFIX: &str = "sfx_";

const GENERATED_PREFIXES: &[&str] = &[SPEECH_PREFIX, SFX_PREFIX];
const GENERATED_EXTENSIONS: &[&str] = &["mp3", "opus", "wav", "pcm", "ulaw", "alaw"];

/// Write `data` to `<output_dir>/<YYYY-MM-DD>/<prefix><timestamp>_<id>.<ext>`.
///
/// The write goes to a `.part` file first and is renamed into place, so a
/// reader never observes a half-written audio file. Returns the final path.
pub async fn save_audio(
    output_dir: &Path,
    prefix: &str,
    extension: &str,
    data: &[u8],
) -> std::io::Result<PathBuf> {
    let now = chrono::Local::now();
    let date_dir = output_dir.join(now.format("%Y-%m-%d").to_string());
    tokio::fs::create_dir_all(&date_dir).await?;

    let unique = uuid::Uuid::new_v4().simple().to_string();
    let filename = format!(
        "{prefix}{}_{}.{extension}",
        now.format("%Y%m%d_%H%M%S"),
        &unique[..8]
    );
    let final_path = date_dir.join(&filename);
    let tmp_path = date_dir.join(format!("{filename}.part"));

    tokio::fs::write(&tmp_path, data).await?;
    if let Err(e) = tokio::fs::rename(&tmp_path, &final_path).await {
        let _ = tokio::fs::remove_file(&tmp_path).await;
        return Err(e);
    }

    // Prefer an absolute path so callers (and humans) can locate the file.
    Ok(std::path::absolute(&final_path).unwrap_or(final_path))
}

/// Whether a file name matches the pattern of files generated by this server.
pub fn is_generated_file_name(name: &str) -> bool {
    GENERATED_PREFIXES.iter().any(|p| name.starts_with(p))
        && Path::new(name)
            .extension()
            .and_then(|e| e.to_str())
            .is_some_and(|e| GENERATED_EXTENSIONS.contains(&e))
}

fn is_date_dir_name(name: &str) -> bool {
    chrono::NaiveDate::parse_from_str(name, "%Y-%m-%d").is_ok()
}

/// Summary of a cleanup run.
#[derive(Debug, Default, Serialize)]
pub struct CleanupReport {
    pub files_removed: usize,
    pub bytes_removed: u64,
    pub directories_removed: usize,
    pub dry_run: bool,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub errors: Vec<String>,
}

/// Delete generated audio files under `dir` (top level and dated
/// subdirectories). When `older_than` is set, only files whose modification
/// time is at least that old are removed. Empty dated subdirectories are
/// removed afterwards. With `dry_run`, nothing is deleted and the report says
/// what would have been.
pub async fn clear_generated(
    dir: &Path,
    older_than: Option<Duration>,
    dry_run: bool,
) -> CleanupReport {
    let mut report = CleanupReport {
        dry_run,
        ..Default::default()
    };
    if !tokio::fs::try_exists(dir).await.unwrap_or(false) {
        return report;
    }
    let cutoff = older_than.and_then(|d| SystemTime::now().checked_sub(d));

    let mut dirs_to_scan = vec![dir.to_path_buf()];
    let mut dated_dirs = Vec::new();
    if let Ok(mut rd) = tokio::fs::read_dir(dir).await {
        while let Ok(Some(entry)) = rd.next_entry().await {
            let name = entry.file_name().to_string_lossy().to_string();
            if let Ok(ft) = entry.file_type().await
                && ft.is_dir()
                && is_date_dir_name(&name)
            {
                dirs_to_scan.push(entry.path());
                dated_dirs.push(entry.path());
            }
        }
    }

    for d in &dirs_to_scan {
        let mut rd = match tokio::fs::read_dir(d).await {
            Ok(rd) => rd,
            Err(e) => {
                report.errors.push(format!("{}: {e}", d.display()));
                continue;
            },
        };
        while let Ok(Some(entry)) = rd.next_entry().await {
            let name = entry.file_name().to_string_lossy().to_string();
            if !is_generated_file_name(&name) {
                continue;
            }
            // symlink_metadata: never follow links out of the output dir.
            let Ok(meta) = tokio::fs::symlink_metadata(entry.path()).await else {
                continue;
            };
            if !meta.is_file() {
                continue;
            }
            if let Some(cutoff) = cutoff
                && meta.modified().map(|m| m > cutoff).unwrap_or(true)
            {
                continue;
            }
            if !dry_run && let Err(e) = tokio::fs::remove_file(entry.path()).await {
                report
                    .errors
                    .push(format!("{}: {e}", entry.path().display()));
                continue;
            }
            report.files_removed += 1;
            report.bytes_removed += meta.len();
        }
    }

    if !dry_run {
        for d in dated_dirs {
            // remove_dir only succeeds on empty directories, which is exactly
            // the behaviour we want (user files are left alone).
            if tokio::fs::remove_dir(&d).await.is_ok() {
                report.directories_removed += 1;
            }
        }
    }

    report
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_name_matching() {
        assert!(is_generated_file_name(
            "speech_20260101_120000_abcd1234.mp3"
        ));
        assert!(is_generated_file_name("sfx_20260101_120000_abcd1234.wav"));
        assert!(!is_generated_file_name("speech_x.txt"));
        assert!(!is_generated_file_name("notes.mp3"));
        assert!(!is_generated_file_name("speech_x.mp3.part"));
    }

    #[tokio::test]
    async fn save_then_clear() {
        let tmp = tempfile::tempdir().unwrap();
        let p = save_audio(tmp.path(), SPEECH_PREFIX, "mp3", b"ID3data")
            .await
            .unwrap();
        assert!(p.exists());
        assert_eq!(std::fs::read(&p).unwrap(), b"ID3data");
        let name = p.file_name().unwrap().to_string_lossy().to_string();
        assert!(is_generated_file_name(&name));

        // A user file in the same dated directory must survive.
        let user_file = p.parent().unwrap().join("keep_me.mp3");
        std::fs::write(&user_file, b"x").unwrap();

        let dry = clear_generated(tmp.path(), None, true).await;
        assert_eq!(dry.files_removed, 1);
        assert!(p.exists());

        // Age filter: the file is brand new, so nothing is removed.
        let aged = clear_generated(tmp.path(), Some(Duration::from_secs(3600)), false).await;
        assert_eq!(aged.files_removed, 0);
        assert!(p.exists());

        let real = clear_generated(tmp.path(), None, false).await;
        assert_eq!(real.files_removed, 1);
        assert_eq!(real.bytes_removed, 7);
        assert!(!p.exists());
        assert!(user_file.exists());
        // Directory still holds the user file, so it is kept.
        assert_eq!(real.directories_removed, 0);
    }

    #[tokio::test]
    async fn clear_missing_dir_is_noop() {
        let tmp = tempfile::tempdir().unwrap();
        let r = clear_generated(&tmp.path().join("nope"), None, false).await;
        assert_eq!(r.files_removed, 0);
        assert!(r.errors.is_empty());
    }
}
