//! MCP tool definitions for BioForge.
//!
//! Each tool is a thin adapter: it deserializes its arguments into a typed
//! struct (so missing, mistyped or out-of-range values become clean
//! `InvalidParameters` errors instead of being silently coerced), delegates
//! to [`Lab`], and converts the outcome (see [`LabError`] for the error
//! mapping). Mutating tools are recorded in the audit log when one is
//! configured.
//!
//! Schemas are hand-written rather than generated by `#[mcp_tool]` because
//! they carry `enum` values and numeric bounds the macro cannot express.

use std::sync::Arc;

use async_trait::async_trait;
use bioforge_types::protocol::{LightingMode, ThermalZone};
use mcp_core::prelude::*;
use serde::de::{DeserializeOwned, Error as _};
use serde::{Deserialize, Deserializer};
use serde_json::{Value, json};

use crate::error::{LabError, LabResult};
use crate::lab::{Lab, MAX_WAIT_SECONDS};

/// Deserialize tool arguments into `T`, mapping failures to
/// `InvalidParameters` with serde's field-level message.
fn parse_args<T: DeserializeOwned>(tool: &str, args: Value) -> Result<T> {
    // Clients may send `null` or omit arguments for parameterless tools.
    let args = if args.is_null() { json!({}) } else { args };
    serde_json::from_value(args).map_err(|e| MCPError::InvalidParameters(format!("{tool}: {e}")))
}

/// Accept integers, and floats with no fractional part (LLM clients often
/// send `45.0` for an integer field), rejecting anything lossy.
fn lenient_u64<'de, D: Deserializer<'de>>(d: D) -> std::result::Result<u64, D::Error> {
    let v = Value::deserialize(d)?;
    if let Some(u) = v.as_u64() {
        return Ok(u);
    }
    match v.as_f64() {
        Some(f) if f.fract() == 0.0 && f >= 0.0 && f <= u64::MAX as f64 => Ok(f as u64),
        Some(f) => Err(D::Error::custom(format!(
            "expected a non-negative integer, got {f}"
        ))),
        None => Err(D::Error::custom(format!(
            "expected a non-negative integer, got {v}"
        ))),
    }
}

fn lenient_u32<'de, D: Deserializer<'de>>(d: D) -> std::result::Result<u32, D::Error> {
    let n = lenient_u64(d)?;
    u32::try_from(n)
        .map_err(|_| D::Error::custom(format!("integer {n} exceeds the maximum of {}", u32::MAX)))
}

fn lenient_opt_u64<'de, D: Deserializer<'de>>(d: D) -> std::result::Result<Option<u64>, D::Error> {
    let v = Option::<Value>::deserialize(d)?;
    match v {
        None | Some(Value::Null) => Ok(None),
        Some(v) => lenient_u64(v).map(Some).map_err(D::Error::custom),
    }
}

fn lenient_opt_u32<'de, D: Deserializer<'de>>(d: D) -> std::result::Result<Option<u32>, D::Error> {
    let v = Option::<Value>::deserialize(d)?;
    match v {
        None | Some(Value::Null) => Ok(None),
        Some(v) => lenient_u32(v).map(Some).map_err(D::Error::custom),
    }
}

// ============================================================================
// Typed arguments
// ============================================================================

#[derive(Deserialize)]
struct DispenseArgs {
    target: String,
    volume_ul: f64,
    reagent: String,
    flow_rate: Option<f64>,
}

#[derive(Deserialize)]
struct AspirateArgs {
    source: String,
    volume_ul: f64,
    flow_rate: Option<f64>,
}

#[derive(Deserialize)]
struct MixArgs {
    target: String,
    volume_ul: f64,
    #[serde(deserialize_with = "lenient_u32")]
    cycles: u32,
    flow_rate: Option<f64>,
}

#[derive(Deserialize)]
struct MoveToArgs {
    x_mm: f64,
    y_mm: f64,
    z_mm: Option<f64>,
}

#[derive(Deserialize)]
struct NoArgs {}

#[derive(Deserialize)]
struct SetTemperatureArgs {
    zone: ThermalZone,
    target_c: f64,
    #[serde(default, deserialize_with = "lenient_opt_u64")]
    hold_seconds: Option<u64>,
}

#[derive(Deserialize)]
struct HeatShockArgs {
    ramp_to_c: f64,
    #[serde(deserialize_with = "lenient_u64")]
    hold_s: u64,
    return_to_c: f64,
}

#[derive(Deserialize)]
struct IncubateArgs {
    zone: ThermalZone,
    target_c: f64,
    duration_hours: f64,
}

#[derive(Deserialize)]
struct CaptureArgs {
    plate_id: String,
    lighting_mode: Option<LightingMode>,
}

#[derive(Deserialize)]
struct CountColoniesArgs {
    plate_id: String,
    image_id: String,
    #[serde(default, deserialize_with = "lenient_opt_u32")]
    min_area_px: Option<u32>,
    #[serde(default, deserialize_with = "lenient_opt_u32")]
    max_area_px: Option<u32>,
}

#[derive(Deserialize)]
struct LoadProtocolArgs {
    protocol_id: String,
}

#[derive(Deserialize)]
struct HumanActionArgs {
    description: String,
    #[serde(deserialize_with = "lenient_u64")]
    timeout_min: u64,
    #[serde(default, deserialize_with = "lenient_opt_u64")]
    wait_seconds: Option<u64>,
}

#[derive(Deserialize)]
struct HumanStatusArgs {
    action_id: String,
    #[serde(default, deserialize_with = "lenient_opt_u64")]
    wait_seconds: Option<u64>,
}

#[derive(Deserialize)]
struct EmergencyStopArgs {
    reason: Option<String>,
}

// ============================================================================
// Tool plumbing
// ============================================================================

/// Convert a lab outcome into an MCP result, auditing mutating calls.
async fn finish(
    lab: &Lab,
    tool: &str,
    audited: bool,
    raw_args: &Value,
    outcome: LabResult<Value>,
) -> Result<ToolResult> {
    if audited {
        let audit_outcome = match &outcome {
            Ok(v) => Ok(v),
            Err(e) => Err(e.to_string()),
        };
        lab.audit(tool, raw_args, audit_outcome).await;
    }
    match outcome {
        Ok(v) => ToolResult::json(&v),
        Err(e) => {
            if matches!(e, LabError::Refused(_)) {
                tracing::warn!(tool, "{e}");
            }
            e.into_mcp()
        },
    }
}

/// Define a tool struct holding `Arc<Lab>` whose `execute` parses `$args`
/// into `$ty` and evaluates `$body` (a future yielding `LabResult<Value>`).
macro_rules! lab_tool {
    (
        $tool:ident, $name:literal, audited = $audited:literal,
        description = $desc:expr,
        schema = $schema:expr,
        |$lab:ident, $args:ident: $ty:ty| $body:expr
    ) => {
        struct $tool(Arc<Lab>);

        #[async_trait]
        impl Tool for $tool {
            fn name(&self) -> &str {
                $name
            }

            fn description(&self) -> &str {
                $desc
            }

            fn schema(&self) -> Value {
                $schema
            }

            async fn execute(&self, raw: Value) -> Result<ToolResult> {
                let $args: $ty = parse_args($name, raw.clone())?;
                let $lab: &Lab = &self.0;
                let outcome = $body.await;
                finish($lab, $name, $audited, &raw, outcome).await
            }
        }
    };
}

fn flow_rate_schema() -> Value {
    json!({
        "type": "number",
        "exclusiveMinimum": 0,
        "description": "Flow rate in uL/s (optional; pump default if omitted). Must not exceed the configured max_flow_rate_ul_s."
    })
}

fn zone_schema() -> Value {
    json!({
        "type": "string",
        "enum": ["cold", "warm"],
        "description": "Thermal zone"
    })
}

fn wait_schema() -> Value {
    json!({
        "type": "integer",
        "minimum": 0,
        "maximum": MAX_WAIT_SECONDS,
        "default": 0,
        "description": "Block up to this many seconds for the operator to confirm (default 0 = return immediately)"
    })
}

// ============================================================================
// Liquid handling
// ============================================================================

lab_tool!(
    DispenseTool,
    "dispense",
    audited = true,
    description = "Dispense a volume to a target well or plate position. Validates volume and flow rate against safety limits and counts the volume against the per-run dispense budget.",
    schema = json!({
        "type": "object",
        "properties": {
            "target": { "type": "string", "description": "Target well or plate position (e.g. 'plate_1:A1'). Letters, digits, '_', '-', ':', '.', spaces." },
            "volume_ul": { "type": "number", "description": "Volume to dispense in microliters (within the configured min/max single-dispense volume)" },
            "reagent": { "type": "string", "description": "Reagent label (e.g. 'lb_broth')" },
            "flow_rate": flow_rate_schema()
        },
        "required": ["target", "volume_ul", "reagent"]
    }),
    |lab, a: DispenseArgs| lab.dispense(&a.target, a.volume_ul, &a.reagent, a.flow_rate)
);

lab_tool!(
    AspirateTool,
    "aspirate",
    audited = true,
    description = "Aspirate a volume from a source container. Validates volume and flow rate against safety limits.",
    schema = json!({
        "type": "object",
        "properties": {
            "source": { "type": "string", "description": "Source container label" },
            "volume_ul": { "type": "number", "description": "Volume to aspirate in microliters" },
            "flow_rate": flow_rate_schema()
        },
        "required": ["source", "volume_ul"]
    }),
    |lab, a: AspirateArgs| lab.aspirate(&a.source, a.volume_ul, a.flow_rate)
);

lab_tool!(
    MixTool,
    "mix",
    audited = true,
    description = "Mix in place with repeated aspirate/dispense strokes. Does not count against the dispense budget.",
    schema = json!({
        "type": "object",
        "properties": {
            "target": { "type": "string", "description": "Target well to mix" },
            "volume_ul": { "type": "number", "description": "Volume per stroke in microliters" },
            "cycles": { "type": "integer", "minimum": 1, "description": "Number of aspirate/dispense cycles (at most the configured max_mix_cycles)" },
            "flow_rate": flow_rate_schema()
        },
        "required": ["target", "volume_ul", "cycles"]
    }),
    |lab, a: MixArgs| lab.mix(&a.target, a.volume_ul, a.cycles, a.flow_rate)
);

// ============================================================================
// Motion
// ============================================================================

lab_tool!(
    MoveToTool,
    "move_to",
    audited = true,
    description = "Move the gantry to an absolute position. Validates against the enclosure bounds; z defaults to the configured safe travel height.",
    schema = json!({
        "type": "object",
        "properties": {
            "x_mm": { "type": "number", "minimum": 0, "description": "X position in mm" },
            "y_mm": { "type": "number", "minimum": 0, "description": "Y position in mm" },
            "z_mm": { "type": "number", "minimum": 0, "description": "Z position in mm (defaults to the safe travel height)" }
        },
        "required": ["x_mm", "y_mm"]
    }),
    |lab, a: MoveToArgs| lab.move_to(a.x_mm, a.y_mm, a.z_mm)
);

lab_tool!(
    HomeGantryTool,
    "home_gantry",
    audited = true,
    description = "Home all gantry axes to (0, 0, 0).",
    schema = json!({ "type": "object", "properties": {} }),
    |lab, _a: NoArgs| lab.home_gantry()
);

// ============================================================================
// Thermal
// ============================================================================

lab_tool!(
    SetTemperatureTool,
    "set_temperature",
    audited = true,
    description = "Set a thermal zone's setpoint and read it back. The setpoint persists after the call; an active incubation on the zone is cancelled.",
    schema = json!({
        "type": "object",
        "properties": {
            "zone": zone_schema(),
            "target_c": { "type": "number", "description": "Target temperature in Celsius (within the configured tool_min_c..tool_max_c)" },
            "hold_seconds": { "type": "integer", "minimum": 1, "description": "Intended hold duration (optional, advisory; validated but not timed by the server)" }
        },
        "required": ["zone", "target_c"]
    }),
    |lab, a: SetTemperatureArgs| lab.set_temperature(a.zone, a.target_c, a.hold_seconds)
);

lab_tool!(
    HeatShockTool,
    "heat_shock",
    audited = true,
    description = "Run an atomic heat-shock sequence in the warm zone: ramp to ramp_to_c, hold for hold_s, return to return_to_c. Fails if the measured temperature deviates beyond max_overshoot_c.",
    schema = json!({
        "type": "object",
        "properties": {
            "ramp_to_c": { "type": "number", "description": "Heat-shock temperature in Celsius" },
            "hold_s": { "type": "integer", "minimum": 1, "description": "Hold duration in seconds (at most max_heat_shock_hold_s)" },
            "return_to_c": { "type": "number", "description": "Temperature to return to after the hold" }
        },
        "required": ["ramp_to_c", "hold_s", "return_to_c"]
    }),
    |lab, a: HeatShockArgs| lab.heat_shock(a.ramp_to_c, a.hold_s, a.return_to_c)
);

lab_tool!(
    IncubateTool,
    "incubate",
    audited = true,
    description = "Start a long-duration temperature hold on a zone. Returns immediately with the end time; poll get_system_status for progress.",
    schema = json!({
        "type": "object",
        "properties": {
            "zone": zone_schema(),
            "target_c": { "type": "number", "description": "Incubation temperature in Celsius" },
            "duration_hours": { "type": "number", "exclusiveMinimum": 0, "description": "Incubation duration in hours (at most max_incubation_hours)" }
        },
        "required": ["zone", "target_c", "duration_hours"]
    }),
    |lab, a: IncubateArgs| lab.incubate(a.zone, a.target_c, a.duration_hours)
);

// ============================================================================
// Imaging
// ============================================================================

lab_tool!(
    CaptureImageTool,
    "capture_plate_image",
    audited = true,
    description = "Capture a plate image (white, uv_blue for GFP, or dark_field lighting) and register it for count_colonies. Allowed during an emergency stop.",
    schema = json!({
        "type": "object",
        "properties": {
            "plate_id": { "type": "string", "description": "Plate identifier (letters, digits, '_', '-'; max 64 chars)" },
            "lighting_mode": {
                "type": "string",
                "enum": ["white", "uv_blue", "dark_field"],
                "default": "white",
                "description": "Illumination mode"
            }
        },
        "required": ["plate_id"]
    }),
    |lab, a: CaptureArgs| lab
        .capture_plate_image(&a.plate_id, a.lighting_mode.unwrap_or(LightingMode::White))
);

lab_tool!(
    CountColoniesTool,
    "count_colonies",
    audited = true,
    description = "Run colony counting on an image captured by capture_plate_image. Returns count, mean diameter, size distribution and colony coordinates. NOTE: the bioforge-vision pipeline is currently a placeholder (fixed result).",
    schema = json!({
        "type": "object",
        "properties": {
            "plate_id": { "type": "string", "description": "Plate identifier" },
            "image_id": { "type": "string", "description": "Image id from capture_plate_image, or 'latest' for the plate's most recent image" },
            "min_area_px": { "type": "integer", "minimum": 1, "description": "Minimum blob area in pixels to count as a colony (default 50)" },
            "max_area_px": { "type": "integer", "minimum": 2, "description": "Maximum blob area in pixels (default 5000)" }
        },
        "required": ["plate_id", "image_id"]
    }),
    |lab, a: CountColoniesArgs| lab.count_colonies(
        &a.plate_id,
        &a.image_id,
        a.min_area_px,
        a.max_area_px
    )
);

// ============================================================================
// Protocols
// ============================================================================

lab_tool!(
    ListProtocolsTool,
    "list_protocols",
    audited = false,
    description = "List protocol files available to load_protocol (including custom/ protocols) with name and step count.",
    schema = json!({ "type": "object", "properties": {} }),
    |lab, _a: NoArgs| lab.list_protocols()
);

lab_tool!(
    LoadProtocolTool,
    "load_protocol",
    audited = true,
    description = "Load a protocol TOML file and validate every step against the current safety limits and workspace bounds. On success it becomes the active protocol; on failure the per-step issues are returned and nothing is loaded.",
    schema = json!({
        "type": "object",
        "properties": {
            "protocol_id": { "type": "string", "description": "Protocol id: file name without .toml, optionally prefixed with 'custom/' (see list_protocols)" }
        },
        "required": ["protocol_id"]
    }),
    |lab, a: LoadProtocolArgs| lab.load_protocol(&a.protocol_id)
);

// ============================================================================
// Status, gates, e-stop
// ============================================================================

lab_tool!(
    GetSystemStatusTool,
    "get_system_status",
    audited = false,
    description = "Return sensor readings, thermal setpoints and incubations, gantry position, e-stop state, dispense budget, active protocol, pending human actions and the configured safety limits.",
    schema = json!({ "type": "object", "properties": {} }),
    |lab, _a: NoArgs| lab.system_status()
);

lab_tool!(
    RequestHumanActionTool,
    "request_human_action",
    audited = true,
    description = "Open a human-in-the-loop gate. While it is pending every actuator tool is refused. The operator confirms out of band (confirmation file); the gate otherwise expires after timeout_min. Optionally blocks up to wait_seconds for confirmation.",
    schema = json!({
        "type": "object",
        "properties": {
            "description": { "type": "string", "description": "What the operator must do" },
            "timeout_min": { "type": "integer", "minimum": 1, "maximum": crate::protocols::MAX_HUMAN_TIMEOUT_MIN, "description": "Minutes before the gate expires" },
            "wait_seconds": wait_schema()
        },
        "required": ["description", "timeout_min"]
    }),
    |lab, a: HumanActionArgs| lab.request_human_action(
        &a.description,
        a.timeout_min,
        a.wait_seconds.unwrap_or(0)
    )
);

lab_tool!(
    GetHumanActionStatusTool,
    "get_human_action_status",
    audited = false,
    description = "Check (and optionally wait for) a human action opened by request_human_action: pending_human_approval, confirmed, timed_out or cancelled_by_emergency_stop.",
    schema = json!({
        "type": "object",
        "properties": {
            "action_id": { "type": "string", "description": "action_id returned by request_human_action" },
            "wait_seconds": wait_schema()
        },
        "required": ["action_id"]
    }),
    |lab, a: HumanStatusArgs| lab.human_action_status(&a.action_id, a.wait_seconds.unwrap_or(0))
);

lab_tool!(
    EmergencyStopTool,
    "emergency_stop",
    audited = true,
    description = "Immediately halt all actuators (cancelling in-flight commands), safe the thermal zones and latch the e-stop. The latch can only be cleared by restarting the server.",
    schema = json!({
        "type": "object",
        "properties": {
            "reason": { "type": "string", "description": "Why the stop was triggered (optional, recorded in status and audit log)" }
        }
    }),
    |lab, a: EmergencyStopArgs| lab.emergency_stop(a.reason.as_deref())
);

/// Build every BioForge tool around a shared [`Lab`].
pub fn all_tools(lab: Arc<Lab>) -> Vec<BoxedTool> {
    vec![
        Arc::new(DispenseTool(lab.clone())),
        Arc::new(AspirateTool(lab.clone())),
        Arc::new(MixTool(lab.clone())),
        Arc::new(MoveToTool(lab.clone())),
        Arc::new(HomeGantryTool(lab.clone())),
        Arc::new(SetTemperatureTool(lab.clone())),
        Arc::new(HeatShockTool(lab.clone())),
        Arc::new(IncubateTool(lab.clone())),
        Arc::new(CaptureImageTool(lab.clone())),
        Arc::new(CountColoniesTool(lab.clone())),
        Arc::new(ListProtocolsTool(lab.clone())),
        Arc::new(LoadProtocolTool(lab.clone())),
        Arc::new(GetSystemStatusTool(lab.clone())),
        Arc::new(RequestHumanActionTool(lab.clone())),
        Arc::new(GetHumanActionStatusTool(lab.clone())),
        Arc::new(EmergencyStopTool(lab)),
    ]
}
