name: 'PR Review Fix'
description: 'Apply fixes based on AI review feedback from Gemini and Codex reviews'

inputs:
  pr_number:
    description: 'PR number'
    required: true
  branch_name:
    description: 'Branch name to push fixes to'
    required: true
  max_iterations:
    description: 'Maximum fix iterations'
    required: false
    default: '5'
  github_token:
    description: 'GitHub token for iteration check (read-only)'
    required: true

outputs:
  made_changes:
    description: 'Whether changes were made'
    value: ${{ steps.agent-fix.outputs.made_changes || steps.skip.outputs.made_changes || 'false' }}
  iteration_count:
    description: 'Current iteration count'
    value: ${{ steps.iteration.outputs.iteration_count }}
  exceeded_max:
    description: 'Whether max iterations were exceeded'
    value: ${{ steps.iteration.outputs.exceeded_max }}

runs:
  using: 'composite'
  steps:
    - name: Ensure clean working directory
      shell: bash
      run: |
        git checkout -- . 2>/dev/null || true
        git clean -fd 2>/dev/null || true
        echo "Working directory reset to clean state"

    - name: Check iteration count
      id: iteration
      uses: ./.github/actions/agent-iteration-check
      with:
        pr_number: ${{ inputs.pr_number }}
        max_iterations: ${{ inputs.max_iterations }}
        agent_type: 'review-fix'
        github_token: ${{ inputs.github_token }}

    - name: Skip if max iterations reached
      id: skip
      if: steps.iteration.outputs.exceeded_max == 'true'
      shell: bash
      run: |
        echo "Maximum iterations (${{ inputs.max_iterations }}) reached for review-fix agent. Manual intervention required."
        echo "made_changes=false" >> $GITHUB_OUTPUT
        exit 0

    - name: Download review artifacts
      if: steps.iteration.outputs.should_skip != 'true'
      uses: actions/download-artifact@v6
      continue-on-error: true
      with:
        pattern: '*-review-${{ github.run_id }}-${{ github.run_attempt }}'
        merge-multiple: true
        path: .

    - name: Setup Node.js
      if: steps.iteration.outputs.should_skip != 'true'
      uses: ./.github/actions/setup-nodejs

    - name: Set Docker user environment
      if: steps.iteration.outputs.should_skip != 'true'
      shell: bash
      run: source ./automation/setup/docker/set-docker-user.sh

    - name: Run agent review response
      id: agent-fix
      if: steps.iteration.outputs.should_skip != 'true'
      shell: bash
      env:
        GEMINI_REVIEW_PATH: gemini-review.md
        CODEX_REVIEW_PATH: codex-review.md
        PR_NUMBER: ${{ inputs.pr_number }}
        BRANCH_NAME: ${{ inputs.branch_name }}
        ITERATION_COUNT: ${{ steps.iteration.outputs.iteration_count }}
      run: |
        echo "Running agent review response..."
        ./automation/ci-cd/agent-review-response.sh \
          "$PR_NUMBER" \
          "$BRANCH_NAME" \
          "$ITERATION_COUNT" \
          "${{ inputs.max_iterations }}"

    - name: Cleanup output directories
      if: always()
      shell: bash
      run: |
        if [ -f "./automation/ci-cd/cleanup-outputs.sh" ]; then
          ./automation/ci-cd/cleanup-outputs.sh
        fi
