[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sleeper-detection"
version = "2.0.0"
description = "Comprehensive evaluation framework for detecting sleeper agents in language models"
readme = "README.md"
authors = [
    {name = "Andrew Altimit"},
]
license = {text = "MIT"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
requires-python = ">=3.10"
dependencies = [
    # Core ML Libraries (minimal runtime)
    "torch>=2.1.0",
    "numpy>=1.24.0",
    "transformer-lens>=1.9.0",
    "transformers>=4.34.0",
    "einops>=0.7.0",
    "fancy-einsum>=0.0.3",
    # Model Management
    "huggingface-hub>=0.20.0",
    "psutil>=5.9.0",
    # API Server
    "fastapi>=0.104.0",
    "uvicorn>=0.24.0",
    "pydantic>=2.0.0",
    # Visualization
    "matplotlib>=3.6.0",
    "plotly>=5.0.0",
    "seaborn>=0.12.0",
    "pandas>=2.0.0",
    # Utilities
    "loguru>=0.7.0",
]

[project.optional-dependencies]
dev = [
    # Testing
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.1.0",
    # Notebook Support
    "jupyter>=1.0.0",
    "nbconvert>=7.0.0",
    # Type Checking
    "mypy>=1.5.0",
    "types-requests",
    # Code Quality
    "black>=23.0.0",
    "isort>=5.12.0",
    "flake8>=6.0.0",
    "pylint>=2.17.0",
    # Documentation
    "sphinx>=7.0.0",
    "sphinx-rtd-theme>=1.3.0",
]
evaluation = [
    # Additional dependencies for full evaluation system
    "scikit-learn>=1.3.0",
    # Report Generation
    "jinja2>=3.1.0",
    # Configuration
    "pyyaml>=6.0",
    "python-dotenv>=1.0.0",
    # CLI
    "colorama>=0.4.6",
    "tabulate>=0.9.0",
    "tqdm>=4.66.0",
    # Utilities
    "aiofiles>=23.2.1",
    "httpx>=0.25.0",
    "psutil>=5.9.0",
    "python-multipart>=0.0.6",
]
# The 'all' group combines runtime, dev, and evaluation for complete environment
all = [
    # Include all dependencies from other groups
    "scikit-learn>=1.3.0",
    "jinja2>=3.1.0",
    "pyyaml>=6.0",
    "python-dotenv>=1.0.0",
    "colorama>=0.4.6",
    "tabulate>=0.9.0",
    "tqdm>=4.66.0",
    "aiofiles>=23.2.1",
    "httpx>=0.25.0",
    "psutil>=5.9.0",
    "python-multipart>=0.0.6",
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.1.0",
    "jupyter>=1.0.0",
    "nbconvert>=7.0.0",
    "mypy>=1.5.0",
    "types-requests",
    "black>=23.0.0",
    "isort>=5.12.0",
    "flake8>=6.0.0",
    "pylint>=2.17.0",
    "sphinx>=7.0.0",
    "sphinx-rtd-theme>=1.3.0",
]

[project.urls]
Homepage = "https://github.com/AndrewAltimit/template-repo"
Documentation = "https://github.com/AndrewAltimit/template-repo/tree/main/packages/sleeper_detection/docs"
Issues = "https://github.com/AndrewAltimit/template-repo/issues"

[project.scripts]
sleeper-detect = "packages.sleeper_detection.cli:main"

[tool.setuptools]
packages = ["sleeper_detection"]
package-dir = {"sleeper_detection" = "."}

[tool.setuptools.package-data]
sleeper_detection = [
    "test_suites/*.yaml",
    "configs/*.json",
    "docs/*.md",
]

[tool.black]
line-length = 127
target-version = ['py310', 'py311']

[tool.flake8]
max-line-length = 127
exclude = [".git", "__pycache__", "build", "dist"]
ignore = ["E203", "W503"]

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_functions = ["test_*"]
asyncio_mode = "auto"
