[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sleeper-detection"
version = "2.0.0"
description = "Comprehensive evaluation framework for detecting sleeper agents in language models"
readme = "README.md"
authors = [
    {name = "Andrew Altimit"},
]
license = {text = "MIT"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
requires-python = ">=3.10"
dependencies = [
    "torch>=2.2.0",
    "transformers>=4.35.0",
    "einops>=0.7.0",
    "numpy>=1.24.0",
    "pandas>=2.0.0",
    "scikit-learn>=1.3.0",
    "jinja2>=3.1.0",
    "matplotlib>=3.7.0",
    "seaborn>=0.12.0",
    "plotly>=5.17.0",
    "pyyaml>=6.0",
    "python-dotenv>=1.0.0",
    "colorama>=0.4.6",
    "tabulate>=0.9.0",
    "tqdm>=4.66.0",
    "aiofiles>=23.2.1",
    "httpx>=0.25.0",
    "psutil>=5.9.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "black>=23.0.0",
    "flake8>=6.0.0",
    "mypy>=1.0.0",
]
gpu = [
    "torch>=2.2.0+cu118",
]

[project.urls]
Homepage = "https://github.com/AndrewAltimit/template-repo"
Documentation = "https://github.com/AndrewAltimit/template-repo/tree/main/packages/sleeper_detection/docs"
Issues = "https://github.com/AndrewAltimit/template-repo/issues"

[project.scripts]
sleeper-detect = "packages.sleeper_detection.cli:main"

[tool.setuptools]
packages = ["sleeper_detection"]
package-dir = {"sleeper_detection" = "sleeper_detection"}

[tool.setuptools.package-data]
sleeper_detection = [
    "test_suites/*.yaml",
    "configs/*.json",
    "docs/*.md",
]

[tool.black]
line-length = 127
target-version = ['py310', 'py311']

[tool.flake8]
max-line-length = 127
exclude = [".git", "__pycache__", "build", "dist"]
ignore = ["E203", "W503"]

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_functions = ["test_*"]
asyncio_mode = "auto"
