version: '3.8'

services:
  dbr15:
    build:
      context: .
      dockerfile: reference/dockerfiles/dbr15.Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
        DBX_CLI_VERSION: ${DBX_CLI_VERSION_DBR15:-0.245.0}
        TERRAFORM_VERSION: ${TERRAFORM_VERSION_DBR15:-1.11.2}
        TERRAGRUNT_VERSION: ${TERRAGRUNT_VERSION_DBR15:-v0.77.0}
        AWS_CLI_VERSION: ${AWS_CLI_VERSION_DBR15:-2.22.25}
    image: dbr-env:15
    container_name: dbr15
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - SPARK_LOCAL_IP=127.0.0.1
    tty: true
    stdin_open: true
    command: /bin/bash

  dbr16:
    build:
      context: .
      dockerfile: reference/dockerfiles/dbr16.Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
        DBX_CLI_VERSION: ${DBX_CLI_VERSION_DBR16:-0.256.0}
        TERRAFORM_VERSION: ${TERRAFORM_VERSION_DBR16:-1.12.2}
        TERRAGRUNT_VERSION: ${TERRAGRUNT_VERSION_DBR16:-v0.81.10}
        AWS_CLI_VERSION: ${AWS_CLI_VERSION_DBR16:-2.22.25}
    image: dbr-env:16
    container_name: dbr16
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - SPARK_LOCAL_IP=127.0.0.1
    tty: true
    stdin_open: true
    command: /bin/bash
