version: '3.8'

services:
  dbr15:
    build:
      context: .
      dockerfile: reference/dockerfiles/dbr15.Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    image: dbr-env:15
    container_name: dbr15
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    volumes:
      - ./workspace:/workspace
    working_dir: /workspace
    environment:
      - SPARK_LOCAL_IP=127.0.0.1
    command: /bin/bash

  dbr16:
    build:
      context: .
      dockerfile: reference/dockerfiles/dbr16.Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    image: dbr-env:16
    container_name: dbr16
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    volumes:
      - ./workspace:/workspace
    working_dir: /workspace
    environment:
      - SPARK_LOCAL_IP=127.0.0.1
    command: /bin/bash
