version: '3.8'

services:
  dbr15:
    build:
      context: .
      dockerfile: reference/dockerfiles/dbr15.Dockerfile
      args:
        TARGETARCH: ${TARGETARCH:-amd64}
    image: dbr-env:15
    container_name: dbr15-env
    volumes:
      - ./workspace:/workspace
      - ./dist:/dist:ro
    environment:
      - DBR_VERSION=dbr15
    command: /bin/bash
    stdin_open: true
    tty: true

  dbr16:
    build:
      context: .
      dockerfile: reference/dockerfiles/dbr16.Dockerfile
      args:
        TARGETARCH: ${TARGETARCH:-amd64}
    image: dbr-env:16
    container_name: dbr16-env
    volumes:
      - ./workspace:/workspace
      - ./dist:/dist:ro
    environment:
      - DBR_VERSION=dbr16
    command: /bin/bash
    stdin_open: true
    tty: true

  # Test container for building wheels
  builder:
    image: python:3.11-slim
    container_name: dbr-builder
    working_dir: /workspace
    volumes:
      - .:/workspace
    environment:
      - PYTHONUNBUFFERED=1
    command: /workspace/build/scripts/build-wheels.sh
