name: 'Agent Iteration Check'
description: 'Track agent auto-fix iterations to prevent infinite loops'

inputs:
  pr_number:
    description: 'PR number'
    required: true
  max_iterations:
    description: 'Maximum allowed iterations before stopping'
    required: false
    default: '10'
  github_token:
    description: 'GitHub token for API operations'
    required: true

outputs:
  iteration_count:
    description: 'Current iteration count (consecutive agent commits since last human commit)'
    value: ${{ steps.check.outputs.iteration_count }}
  is_agent_commit:
    description: 'Whether the last commit was made by an agent'
    value: ${{ steps.check.outputs.is_agent_commit }}
  should_skip:
    description: 'Whether to skip this run (max iterations reached)'
    value: ${{ steps.check.outputs.should_skip }}
  exceeded_max:
    description: 'Whether max iterations have been exceeded'
    value: ${{ steps.check.outputs.exceeded_max }}

runs:
  using: 'composite'
  steps:
    - name: Check iteration count from git history
      id: check
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        PR_NUMBER: ${{ inputs.pr_number }}
        MAX_ITERATIONS: ${{ inputs.max_iterations }}
      run: |
        echo "=== Agent Iteration Check ==="
        echo "PR Number: $PR_NUMBER"
        echo "Max Iterations: $MAX_ITERATIONS"

        # Agent author names to detect
        AGENT_AUTHORS=("AI Review Agent" "AI Pipeline Agent" "AI Agent Bot")

        # Check if last commit is an agent commit
        LAST_COMMIT_AUTHOR=$(git log -1 --format='%an' 2>/dev/null || echo "")
        echo "Last commit author: $LAST_COMMIT_AUTHOR"

        IS_AGENT_COMMIT="false"
        for author in "${AGENT_AUTHORS[@]}"; do
          if [[ "$LAST_COMMIT_AUTHOR" == "$author" ]]; then
            IS_AGENT_COMMIT="true"
            echo "Detected agent commit via author name: $LAST_COMMIT_AUTHOR"
            break
          fi
        done
        echo "is_agent_commit=$IS_AGENT_COMMIT" >> $GITHUB_OUTPUT

        # Count consecutive agent commits from HEAD backwards
        # This resets automatically when a human commits
        echo "Counting consecutive agent commits..."
        ITERATION_COUNT=0

        # Fetch enough commits to cover max_iterations (plus buffer for safety)
        FETCH_LIMIT=$((MAX_ITERATIONS + 10))
        while IFS= read -r author; do
          is_agent="false"
          for agent_author in "${AGENT_AUTHORS[@]}"; do
            if [[ "$author" == "$agent_author" ]]; then
              is_agent="true"
              break
            fi
          done

          if [[ "$is_agent" == "true" ]]; then
            ITERATION_COUNT=$((ITERATION_COUNT + 1))
          else
            # Hit a human commit, stop counting
            echo "Found human commit by: $author (stopping count)"
            break
          fi
        done < <(git log --format='%an' -"$FETCH_LIMIT" 2>/dev/null)

        echo "Consecutive agent commits: $ITERATION_COUNT"

        # Check if max iterations exceeded
        EXCEEDED_MAX="false"
        SHOULD_SKIP="false"
        if [ "$ITERATION_COUNT" -ge "$MAX_ITERATIONS" ]; then
          EXCEEDED_MAX="true"
          SHOULD_SKIP="true"
          echo "WARNING: Max iterations ($MAX_ITERATIONS) reached!"

          # Post a comment to the PR explaining why the agent stopped
          COMMENT_BODY="## Agent Iteration Limit Reached

        The automated review response agent has reached the maximum iteration limit (**${ITERATION_COUNT}/${MAX_ITERATIONS}**).

        **What this means:**
        - The agent has made $ITERATION_COUNT consecutive fix attempts
        - Further automated fixes have been paused to prevent infinite loops
        - Any remaining review feedback requires manual attention

        **To resume automated fixes:**
        - Push a human commit (even a small change) to reset the counter
        - Or add the \`no-auto-fix\` label to disable automated fixes entirely

        ---
        *This is a safety mechanism to prevent runaway automation.*"

          # Post comment using gh CLI (use temp file, not stdin - gh-validator blocks stdin)
          COMMENT_FILE=$(mktemp)
          echo "$COMMENT_BODY" > "$COMMENT_FILE"
          gh pr comment "$PR_NUMBER" --body-file "$COMMENT_FILE" || \
            echo "Warning: Failed to post iteration limit comment"
          rm -f "$COMMENT_FILE"
        fi

        echo "iteration_count=$ITERATION_COUNT" >> $GITHUB_OUTPUT
        echo "exceeded_max=$EXCEEDED_MAX" >> $GITHUB_OUTPUT
        echo "should_skip=$SHOULD_SKIP" >> $GITHUB_OUTPUT

        echo "=== Iteration Check Complete ==="
        echo "  Iteration Count: $ITERATION_COUNT"
        echo "  Is Agent Commit: $IS_AGENT_COMMIT"
        echo "  Should Skip: $SHOULD_SKIP"
        echo "  Exceeded Max: $EXCEEDED_MAX"
