name: 'Agent Iteration Check'
description: 'Track agent auto-fix iterations to prevent infinite loops'

inputs:
  pr_number:
    description: 'PR number for artifact naming'
    required: true
  max_iterations:
    description: 'Maximum allowed iterations before stopping'
    required: false
    default: '5'
  github_token:
    description: 'GitHub token for artifact operations'
    required: true

outputs:
  iteration_count:
    description: 'Current iteration count'
    value: ${{ steps.check.outputs.iteration_count }}
  is_agent_commit:
    description: 'Whether the last commit was made by an agent'
    value: ${{ steps.check.outputs.is_agent_commit }}
  should_skip:
    description: 'Whether to skip this run (max iterations reached or agent commit)'
    value: ${{ steps.check.outputs.should_skip }}
  exceeded_max:
    description: 'Whether max iterations have been exceeded'
    value: ${{ steps.check.outputs.exceeded_max }}

runs:
  using: 'composite'
  steps:
    - name: Check iteration count and commit type
      id: check
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        PR_NUMBER: ${{ inputs.pr_number }}
        MAX_ITERATIONS: ${{ inputs.max_iterations }}
      run: |
        echo "=== Agent Iteration Check ==="
        echo "PR Number: $PR_NUMBER"
        echo "Max Iterations: $MAX_ITERATIONS"

        # Check if last commit is an agent commit
        LAST_COMMIT_MSG=$(git log -1 --format='%s' 2>/dev/null || echo "")
        LAST_COMMIT_AUTHOR=$(git log -1 --format='%an' 2>/dev/null || echo "")

        echo "Last commit message: $LAST_COMMIT_MSG"
        echo "Last commit author: $LAST_COMMIT_AUTHOR"

        IS_AGENT_COMMIT="false"
        if [[ "$LAST_COMMIT_AUTHOR" == "AI Review Agent" ]] || \
           [[ "$LAST_COMMIT_AUTHOR" == "AI Pipeline Agent" ]] || \
           [[ "$LAST_COMMIT_AUTHOR" == "AI Agent Bot" ]]; then
          IS_AGENT_COMMIT="true"
          echo "Detected agent commit via author name: $LAST_COMMIT_AUTHOR"
        fi

        echo "is_agent_commit=$IS_AGENT_COMMIT" >> $GITHUB_OUTPUT

        # Try to download existing iteration artifact
        ARTIFACT_NAME="agent-iteration-pr-${PR_NUMBER}"
        ITERATION_COUNT=0
        LAST_HUMAN_COMMIT=""

        # Create unique temp directory for artifact (prevents race condition on shared runners)
        ITERATION_DIR="/tmp/agent-iteration-${PR_NUMBER}"
        mkdir -p "$ITERATION_DIR"

        # Try to download the artifact using gh cli
        if gh run download --name "$ARTIFACT_NAME" --dir "$ITERATION_DIR" 2>/dev/null; then
          echo "Downloaded existing iteration artifact"
          if [ -f "$ITERATION_DIR/iteration-count.txt" ]; then
            ITERATION_COUNT=$(cat "$ITERATION_DIR/iteration-count.txt")
            echo "Previous iteration count: $ITERATION_COUNT"
          fi
          if [ -f "$ITERATION_DIR/last-human-commit.txt" ]; then
            LAST_HUMAN_COMMIT=$(cat "$ITERATION_DIR/last-human-commit.txt")
            echo "Last human commit: $LAST_HUMAN_COMMIT"
          fi
        else
          echo "No existing iteration artifact found, starting fresh"
        fi

        # Check if there's a new human commit (reset counter)
        if [ "$IS_AGENT_COMMIT" = "false" ]; then
          CURRENT_COMMIT=$(git rev-parse HEAD)
          if [ "$CURRENT_COMMIT" != "$LAST_HUMAN_COMMIT" ]; then
            echo "New human commit detected, resetting iteration counter"
            ITERATION_COUNT=0
            LAST_HUMAN_COMMIT="$CURRENT_COMMIT"
          fi
        else
          # Increment counter for agent commit
          ITERATION_COUNT=$((ITERATION_COUNT + 1))
          echo "Incremented iteration count to: $ITERATION_COUNT"
        fi

        # Check if max iterations exceeded
        # Note: We do NOT skip on agent commits - agent evaluates if new issues exist
        # The iteration counter (max 5) prevents infinite loops
        EXCEEDED_MAX="false"
        SHOULD_SKIP="false"
        if [ "$ITERATION_COUNT" -ge "$MAX_ITERATIONS" ]; then
          EXCEEDED_MAX="true"
          SHOULD_SKIP="true"
          echo "WARNING: Max iterations ($MAX_ITERATIONS) reached!"
        fi

        # Save updated iteration data
        echo "$ITERATION_COUNT" > "$ITERATION_DIR/iteration-count.txt"
        if [ -n "$LAST_HUMAN_COMMIT" ]; then
          echo "$LAST_HUMAN_COMMIT" > "$ITERATION_DIR/last-human-commit.txt"
        fi

        echo "iteration_count=$ITERATION_COUNT" >> $GITHUB_OUTPUT
        echo "exceeded_max=$EXCEEDED_MAX" >> $GITHUB_OUTPUT
        echo "should_skip=$SHOULD_SKIP" >> $GITHUB_OUTPUT

        echo "=== Iteration Check Complete ==="
        echo "  Iteration Count: $ITERATION_COUNT"
        echo "  Is Agent Commit: $IS_AGENT_COMMIT"
        echo "  Should Skip: $SHOULD_SKIP"
        echo "  Exceeded Max: $EXCEEDED_MAX"

    - name: Upload iteration artifact
      uses: actions/upload-artifact@v4
      with:
        name: agent-iteration-pr-${{ inputs.pr_number }}
        path: /tmp/agent-iteration-${{ inputs.pr_number }}/
        retention-days: 7
        overwrite: true
