//! Trigger keyword parsing and prompt-injection hardening.
//!
//! Triggers have the form `[Action]` or `[Action][Agent]` (case-insensitive),
//! e.g. `[Approved][Claude]`. Because a trigger authorizes an AI agent to run
//! with write access, the parser is deliberately conservative:
//!
//! - Text inside fenced code blocks, inline code spans, blockquotes and HTML
//!   comments is ignored. Quoting or documenting a trigger never fires it, and
//!   invisible (HTML comment) text can never authorize anything.
//! - Comments produced by this tool carry [`AGENT_COMMENT_MARKER`] and are
//!   never treated as triggers, even when they are posted under an
//!   allow-listed account (e.g. when the agent token is a maintainer PAT).
//! - Agent/LLM output is passed through [`neutralize_triggers`] before being
//!   posted, so a prompt-injected model cannot emit a live trigger.

use std::sync::LazyLock;

use regex::Regex;

/// Hidden marker appended to comments/issues this tool generates. Content
/// carrying it is never interpreted as a human directive.
pub const AGENT_COMMENT_MARKER: &str = "<!-- github-agents:generated -->";

/// Hidden marker on monitor replies to a trigger. A trigger followed by a
/// reply carrying this marker (from a trusted account) is considered handled.
pub const TRIGGER_RESPONSE_MARKER: &str = "<!-- github-agents:trigger-response -->";

/// Common prefix of all hidden markers above.
const MARKER_PREFIX: &str = "<!-- github-agents:";

/// Visible prefix used on monitor replies (also by releases that predate the
/// hidden markers, which keeps their replies recognized as responses).
pub const LEGACY_AGENT_PREFIX: &str = "[AI Agent]";

/// Pattern for trigger comments: `[Action]` with optional `[Agent]`.
static TRIGGER_PATTERN: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(r"(?i)\[(Approved|Review|Close|Summarize|Debug)\](?:\[([A-Za-z][A-Za-z0-9_-]*)\])?")
        .expect("valid trigger regex")
});

/// Any bracketed keyword that could be interpreted as a command by this tool
/// or by the iteration tracker (`[CONTINUE]`).
static COMMAND_KEYWORD_PATTERN: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(r"(?i)\[(Approved|Review|Close|Summarize|Debug|Continue)\]")
        .expect("valid keyword regex")
});

static HTML_COMMENT_PATTERN: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"(?s)<!--.*?-->").expect("valid html comment regex"));

static INLINE_CODE_PATTERN: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"(`+)[^`]*?(?:`+)").expect("valid inline code regex"));

/// A parsed trigger keyword.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParsedTrigger {
    /// Lowercased action (e.g. `approved`)
    pub action: String,
    /// Lowercased agent name, if one was given
    pub agent: Option<String>,
}

/// Return the text of a comment that is eligible to carry directives.
///
/// Removes HTML comments, fenced code blocks (``` and ~~~), blockquote lines
/// and inline code spans.
pub fn directive_text(text: &str) -> String {
    let without_html = HTML_COMMENT_PATTERN.replace_all(text, " ");

    let mut out = String::with_capacity(without_html.len());
    let mut fence: Option<&str> = None;
    for line in without_html.lines() {
        let trimmed = line.trim_start();
        if let Some(open) = fence {
            if trimmed.starts_with(open) {
                fence = None;
            }
            continue;
        }
        if trimmed.starts_with("```") {
            fence = Some("```");
            continue;
        }
        if trimmed.starts_with("~~~") {
            fence = Some("~~~");
            continue;
        }
        if trimmed.starts_with('>') {
            continue;
        }
        out.push_str(&INLINE_CODE_PATTERN.replace_all(line, " "));
        out.push('\n');
    }
    out
}

/// Parse the first trigger in `text`, ignoring non-directive content.
pub fn parse_trigger(text: &str) -> Option<ParsedTrigger> {
    if text.is_empty() {
        return None;
    }
    let directive = directive_text(text);
    let captures = TRIGGER_PATTERN.captures(&directive)?;
    Some(ParsedTrigger {
        action: captures.get(1)?.as_str().to_lowercase(),
        agent: captures.get(2).map(|m| m.as_str().to_lowercase()),
    })
}

/// Whether `text` contains a directive-eligible `[CONTINUE]` command.
pub fn contains_continue_command(text: &str) -> bool {
    directive_text(text).to_lowercase().contains("[continue]")
}

/// Whether a comment/body was generated by this tool (and must therefore
/// never be interpreted as a human directive).
pub fn is_agent_generated(body: &str) -> bool {
    body.contains(MARKER_PREFIX) || body.trim_start().starts_with(LEGACY_AGENT_PREFIX)
}

/// Whether a comment is a monitor reply to a trigger.
pub fn is_trigger_response(body: &str) -> bool {
    body.contains(TRIGGER_RESPONSE_MARKER) || body.trim_start().starts_with(LEGACY_AGENT_PREFIX)
}

/// Escape any command keyword in untrusted (agent/LLM) output so it renders
/// identically in Markdown but can no longer be parsed as a trigger.
///
/// `[Approved]` becomes `\[Approved\]`.
pub fn neutralize_triggers(text: &str) -> String {
    COMMAND_KEYWORD_PATTERN
        .replace_all(text, r"\[$1\]")
        .into_owned()
}

/// Whether `login` looks like a GitHub App / bot account.
pub fn is_bot_login(login: &str) -> bool {
    let lower = login.to_lowercase();
    lower.ends_with("[bot]") || lower == "github-actions"
}

#[cfg(test)]
mod tests {
    use super::*;

    fn trig(action: &str, agent: Option<&str>) -> Option<ParsedTrigger> {
        Some(ParsedTrigger {
            action: action.to_string(),
            agent: agent.map(String::from),
        })
    }

    #[test]
    fn parses_basic_triggers() {
        assert_eq!(parse_trigger("[Approved]"), trig("approved", None));
        assert_eq!(
            parse_trigger("[Approved][Claude]"),
            trig("approved", Some("claude"))
        );
        assert_eq!(
            parse_trigger("[APPROVED][CLAUDE]"),
            trig("approved", Some("claude"))
        );
        assert_eq!(
            parse_trigger("Looks good. [Review][OpenCode] please"),
            trig("review", Some("opencode"))
        );
        assert_eq!(parse_trigger("[Close]"), trig("close", None));
        assert_eq!(parse_trigger("[summarize]"), trig("summarize", None));
        assert_eq!(
            parse_trigger("[Debug][Crush]"),
            trig("debug", Some("crush"))
        );
    }

    #[test]
    fn rejects_non_triggers() {
        assert_eq!(parse_trigger(""), None);
        assert_eq!(parse_trigger("[InvalidAction]"), None);
        assert_eq!(parse_trigger("Approved"), None);
        assert_eq!(parse_trigger("[Approve]"), None);
        assert_eq!(parse_trigger("( Approved )"), None);
    }

    #[test]
    fn first_trigger_in_comment_wins() {
        assert_eq!(
            parse_trigger("[Summarize] then [Approved][Claude]"),
            trig("summarize", None)
        );
    }

    #[test]
    fn ignores_triggers_in_inline_code() {
        assert_eq!(parse_trigger("reply with `[Approved]` to create PR"), None);
        assert_eq!(parse_trigger("use ``[Approved][Claude]`` syntax"), None);
    }

    #[test]
    fn ignores_triggers_in_fenced_code() {
        let text = "Example:\n```\n[Approved][Claude]\n```\nnothing else";
        assert_eq!(parse_trigger(text), None);
        let text = "~~~md\n[Approved]\n~~~";
        assert_eq!(parse_trigger(text), None);
        // Trigger after the fence closes is honored
        let text = "```\ncode\n```\n[Approved][Claude]";
        assert_eq!(parse_trigger(text), trig("approved", Some("claude")));
    }

    #[test]
    fn unterminated_fence_hides_rest() {
        assert_eq!(parse_trigger("```\n[Approved]"), None);
    }

    #[test]
    fn ignores_triggers_in_blockquotes() {
        assert_eq!(parse_trigger("> [Approved][Claude]\nI disagree"), None);
        assert_eq!(parse_trigger("  > nested [Approved]"), None);
    }

    #[test]
    fn ignores_triggers_in_html_comments() {
        assert_eq!(parse_trigger("<!-- [Approved][Claude] -->"), None);
        assert_eq!(parse_trigger("<!--\n[Approved]\n-->visible"), None);
    }

    #[test]
    fn neutralize_escapes_keywords() {
        let out = neutralize_triggers("Please [Approved][Claude] and [continue] now");
        assert_eq!(out, r"Please \[Approved\][Claude] and \[continue\] now");
        assert_eq!(parse_trigger(&out), None);
        assert!(!contains_continue_command(&out));
        // Unrelated bracket tags are untouched
        assert_eq!(neutralize_triggers("[BUG] [CRITICAL]"), "[BUG] [CRITICAL]");
    }

    #[test]
    fn agent_generated_detection() {
        assert!(is_agent_generated(&format!(
            "hello\n{}",
            AGENT_COMMENT_MARKER
        )));
        assert!(is_agent_generated(&format!(
            "hi {}",
            TRIGGER_RESPONSE_MARKER
        )));
        assert!(is_agent_generated("[AI Agent] Issue closed"));
        assert!(!is_agent_generated("[Approved][Claude]"));

        // Generated content (e.g. a backlog insight) is not a trigger response
        assert!(!is_trigger_response(&format!(
            "insight\n{}",
            AGENT_COMMENT_MARKER
        )));
        assert!(is_trigger_response(&format!(
            "done\n{}",
            TRIGGER_RESPONSE_MARKER
        )));
        assert!(is_trigger_response("  [AI Agent] legacy reply"));
    }

    #[test]
    fn continue_command_detection() {
        assert!(contains_continue_command("[CONTINUE]"));
        assert!(contains_continue_command("Please [continue] the work"));
        assert!(!contains_continue_command("CONTINUE"));
        assert!(!contains_continue_command("comment `[CONTINUE]` to extend"));
        assert!(!contains_continue_command("> [CONTINUE]"));
    }

    #[test]
    fn bot_logins() {
        assert!(is_bot_login("github-actions[bot]"));
        assert!(is_bot_login("github-actions"));
        assert!(is_bot_login("Dependabot[bot]"));
        assert!(!is_bot_login("AndrewAltimit"));
    }
}
