name: AI Agent Board Integration

on:
  schedule:
    # Run every hour to check for board updates
    - cron: '0 * * * *'
  workflow_dispatch: {}  # Allow manual trigger
  pull_request:
    types: [closed]  # Trigger when PR is closed (merged or not)

permissions:
  issues: write
  contents: read
  pull-requests: read

jobs:
  update-board-on-pr-merge:
    name: Update Board on PR Merge
    runs-on: self-hosted
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == true }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update board for merged PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_PROJECTS_TOKEN: ${{ secrets.GITHUB_PROJECTS_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          docker-compose run --rm \
            -e GITHUB_TOKEN \
            -e GITHUB_REPOSITORY \
            -e GITHUB_PROJECTS_TOKEN \
            -e PR_NUMBER \
            -e PR_BODY \
            python-ci bash -c "\
              pip install -e packages/github_ai_agents && \
              python packages/github_ai_agents/bin/update-pr-merge-status.py"

  board-maintenance:
    name: Board Maintenance
    runs-on: self-hosted
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run board maintenance
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_PROJECTS_TOKEN: ${{ secrets.GITHUB_PROJECTS_TOKEN }}
        run: |
          docker-compose run --rm \
            -e GITHUB_TOKEN \
            -e GITHUB_REPOSITORY \
            -e GITHUB_PROJECTS_TOKEN \
            python-ci bash -c "\
              pip install -e packages/github_ai_agents && \
              python packages/github_ai_agents/bin/run-board-maintenance.py"

      - name: Report status
        if: always()
        run: |
          echo "Board maintenance job completed"
