name: Databricks Environment CI

on:
  push:
    branches: [databricks-env-setup]
    paths:
      - 'databricks/**'
      - '.github/workflows/databricks-ci.yml'
  pull_request:
    branches: [databricks-env-setup]
    paths:
      - 'databricks/**'
      - '.github/workflows/databricks-ci.yml'

jobs:
  build-wheels:
    runs-on: [self-hosted, linux]
    container:
      image: python:3.11-slim
      options: --user 1000:1000
    strategy:
      matrix:
        package: [core, ml, cloud, all]

    steps:
      - uses: actions/checkout@v4

      - name: Install build tools
        run: |
          pip install --user --upgrade pip
          pip install --user build twine

      - name: Build wheel for ${{ matrix.package }}
        run: |
          export PATH=$PATH:$HOME/.local/bin
          cd databricks/wheels/dbr-env-${{ matrix.package }}
          python -m build --wheel

      - name: Validate wheel
        run: |
          export PATH=$PATH:$HOME/.local/bin
          cd databricks/wheels/dbr-env-${{ matrix.package }}
          python -m twine check dist/*.whl

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.package }}
          path: databricks/wheels/dbr-env-${{ matrix.package }}/dist/*.whl
          retention-days: 7

  test-python-packages:
    needs: build-wheels
    runs-on: [self-hosted, linux]
    strategy:
      matrix:
        include:
          - dbr-version: dbr15
            python-image: python:3.11-slim
          - dbr-version: dbr16
            python-image: python:3.12
    container:
      image: ${{ matrix.python-image }}
      options: --user 1000:1000

    steps:
      - uses: actions/checkout@v4

      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          pattern: wheel-*
          path: dist/
          merge-multiple: true

      - name: Install wheels
        run: |
          pip install --upgrade pip
          pip install dist/dbr_env_core-*.whl
          pip install dist/dbr_env_ml-*.whl
          pip install dist/dbr_env_cloud-*.whl
          pip install dist/dbr_env_all-*.whl

      - name: Install DBR dependencies
        run: |
          pip install "dbr-env-all[${{ matrix.dbr-version }}]"

      - name: Test imports
        run: |
          python -c "
          from dbr_env_core import get_dbr_info
          from dbr_env_ml import get_ml_info
          from dbr_env_cloud import get_cloud_info
          from dbr_env_all import get_all_info
          print('✓ All imports successful')

          info = get_all_info('${{ matrix.dbr-version }}')
          print(f'DBR Info: {info}')
          "

      - name: Test mock functionality
        run: |
          python -c "
          from dbr_env_core.mock import get_mock_spark_session, get_mock_databricks_client

          # Test mock Spark
          spark = get_mock_spark_session('TestApp')
          df = spark.createDataFrame([{'test': 'data'}])
          print(f'Mock Spark DataFrame count: {df.count()}')

          # Test mock Databricks
          client = get_mock_databricks_client()
          clusters = client.clusters.list()
          print(f'Mock clusters: {len(clusters)}')

          print('✓ Mock tests passed')
          "

      - name: Run validation
        run: |
          python -m dbr_env_all.validate --version ${{ matrix.dbr-version }} --json

  test-scripts:
    runs-on: [self-hosted, linux]
    container:
      image: python:3.11-slim
      options: --user 1000:1000
    steps:
      - uses: actions/checkout@v4

      - name: Test validation script availability
        run: |
          # Note: dbr-validate is provided by the Python package, not a bash script
          # It will be available after installing the dbr-env-all package
          echo "dbr-validate is provided by the Python dbr-env-all package"

      - name: Test pre-installation script
        run: |
          databricks/scripts/dbr-setup-pre --help

      - name: Test post-installation script
        run: |
          databricks/scripts/dbr-setup-post --help

  test-docker-build:
    runs-on: [self-hosted, linux]
    strategy:
      matrix:
        dbr-version: [15, 16]

    steps:
      - uses: actions/checkout@v4

      - name: Build DBR${{ matrix.dbr-version }} Docker image
        run: |
          cd databricks
          docker build -f reference/dockerfiles/dbr${{ matrix.dbr-version }}.Dockerfile \
            -t dbr-test:${{ matrix.dbr-version }} .

      - name: Test container
        run: |
          # Test all tools in a single container run for efficiency
          docker run --rm --user 1000:1000 dbr-test:${{ matrix.dbr-version }} sh -c "
            echo '--- Testing Python ---' && python --version && \
            echo '--- Testing Java ---' && java -version && \
            echo '--- Testing Databricks CLI ---' && databricks --version && \
            echo '--- Testing Terraform ---' && terraform version && \
            echo '--- Testing Terragrunt ---' && terragrunt --version && \
            echo '✓ All tools verified successfully'
          "

  integration-test:
    needs: [test-python-packages, test-scripts]
    runs-on: [self-hosted, linux]
    container:
      image: python:3.11-slim
      options: --user 1000:1000
    steps:
      - uses: actions/checkout@v4

      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          pattern: wheel-*
          path: dist/
          merge-multiple: true

      - name: Run integration test
        run: |
          # Install packages
          pip install --upgrade pip
          pip install dist/*.whl
          pip install "dbr-env-all[dbr15]"

          # Test complete flow
          python -c "
          from dbr_env_all import get_all_info
          from dbr_env_core.mock import get_mock_spark_session

          # Get environment info
          info = get_all_info('dbr15')
          assert 'core' in info
          assert 'ml' in info
          assert 'cloud' in info

          # Test mock Spark
          spark = get_mock_spark_session()
          df = spark.createDataFrame([
              {'name': 'test', 'value': 123}
          ])
          assert df.count() == 1

          print('✓ Integration test passed')
          "
