name: Issue Monitor Agent

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      force_reprocess:
        description: 'Force reprocess issues even if they have existing AI agent comments'
        required: false
        type: boolean
        default: false
  issues:
    types:
      - opened
      - edited
      - labeled

permissions:
  issues: write       # Required to comment on issues and read issue data
  pull-requests: write # Required to create pull requests
  contents: read      # For actions/checkout. Agent uses AI_AGENT_TOKEN with write perms.

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  monitor-issues:
    name: Monitor GitHub Issues
    runs-on: self-hosted
    # Only run if AI agents are enabled AND (manual trigger OR schedule OR issue event)
    # Note: User authorization is handled by the SecurityManager in the Python agent
    if: |
      vars.ENABLE_AI_AGENTS == 'true' && (
        github.event_name == 'workflow_dispatch' ||
        github.event_name == 'schedule' ||
        github.event_name == 'issues'
      )

    steps:
      - name: Security Check - Log Event Details
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          if [ "${{ github.event_name }}" = "issues" ]; then
            echo "Issue Author: ${{ github.event.issue.user.login }}"
            echo "Issue Number: ${{ github.event.issue.number }}"
          fi

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.AI_AGENT_TOKEN }}

      - name: Configure Git
        run: |
          # Set git identity for the AI agent
          git config --global user.name "AI Issue Agent"
          git config --global user.email "ai-agent@localhost"

      - name: Set up Python environment
        run: |
          echo "[INFO] Checking Python environment..."
          python3 --version

          # Install the GitHub AI Agents package
          echo "[INFO] Installing GitHub AI Agents package..."
          pip3 install --user -e ./packages/github_ai_agents

          # Install additional requirements if needed
          echo "[INFO] Installing additional requirements..."
          pip3 install --user -r docker/requirements/requirements-agents.txt

      - name: Build Docker containers for OpenRouter agents
        run: |
          echo "[INFO] Building openrouter-agents container for OpenCode support..."
          docker-compose --profile agents build openrouter-agents
          echo "[INFO] Container build complete"

      - name: Run issue monitor with hybrid agent support
        env:
          # Use AI_AGENT_TOKEN which has write permissions for creating branches/PRs
          GITHUB_TOKEN: ${{ secrets.AI_AGENT_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          ENABLE_AI_AGENTS: ${{ vars.ENABLE_AI_AGENTS }}
          FORCE_REPROCESS: ${{ inputs.force_reprocess || 'false' }}
          # OpenRouter API key for alternative AI agents
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          # List of environment variables whose values should be masked in public comments
          MASK_ENV_VARS: "GITHUB_TOKEN,AI_AGENT_TOKEN,OPENROUTER_API_KEY"
          # Set Python path to include the current directory
          PYTHONPATH: ${{ github.workspace }}
          PYTHONUNBUFFERED: "1"
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          echo "Running issue monitor for repository: $GITHUB_REPOSITORY"
          echo "[INFO] Using hybrid agent support: Claude/Gemini on host, OpenRouter agents in containers"

          # Run the hybrid issue monitor script
          ./automation/monitoring/issues/run-issue-monitor-hybrid.sh || {
              exit_code=$?
              echo "[ERROR] Issue monitor script failed with exit code: $exit_code"
              exit $exit_code
          }

      - name: Log monitoring results
        if: always()
        run: |
          echo "Issue monitoring completed at $(date)"
