name: Issue Monitor Agent

on:
  schedule:
    # Run every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch: {}
  issues:
    types:
      - opened
      - edited
      - labeled

permissions:
  issues: write
  pull-requests: write
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  monitor-issues:
    name: Monitor GitHub Issues
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "AI Issue Agent"
          git config --global user.email "ai-agent@localhost"

      - name: Build AI agents container
        run: |
          docker-compose build ai-agents

      - name: Run issue monitor in container
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          USER_ID: $(id -u)
          GROUP_ID: $(id -g)
        run: |
          echo "Running issue monitor for repository: $GITHUB_REPOSITORY"
          docker-compose run --rm \
            -e GITHUB_TOKEN="$GITHUB_TOKEN" \
            -e GITHUB_REPOSITORY="$GITHUB_REPOSITORY" \
            ai-agents python scripts/agents/issue_monitor.py

      - name: Log monitoring results
        if: always()
        run: |
          echo "Issue monitoring completed at $(date)"
